import React from 'react';
import logo from './logo.svg';
import './App.css';
import '@aws-amplify/ui/dist/style.css';

import Amplify, { API } from 'aws-amplify';
// file generated by the sls plugin
import awsconfig from './aws-exports';
import { withAuthenticator } from 'aws-amplify-react';

Amplify.configure(awsconfig);

function App() {
  const get = async () => {
    console.log('calling GET');
    const response = await API.get(
      'ApiGatewayRestApi', // function defined in our serverless.yml
      '/test',            // the function's path
      { 'responseType': 'text' }
    );
    console.log(`got ${response}`);
    alert(response);
  };
  return (
    <div className="App">
      <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />
        <p>Internal Application behind Login</p>
        <button onClick={get}>GET</button>
      </header>
    </div>
  );
}

export default withAuthenticator(App, true);
